POST http://localhost:8080/api/user/752
Accept: application/json

###
POST localhost:8080/api/inscription
Content-Type: application/json

{
      "email" : "admin@allyrx.com",
      "password": "123456",
      "username": "albert"
}
###
POST localhost:8080/api/user/activation
Content-Type: application/json

{
    "code": "119343"
}